apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1 #initial number of pods
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rlbackend:latest
        imagePullPolicy: Never  
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        ports:
        - containerPort: 8000
        resources:  # Define resource requests and limits for autoscaling
          requests:
            cpu: "35m"  # Requests 250 milliCPU (0.25 vCPU)
          limits:
            cpu: "100m"  # Max CPU limit is 0.5 vCPU
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000  #port inside the cluster
      targetPort: 8000  #port exposed by the backend container
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1  # Minimum number of pods
  maxReplicas: 20  # Maximum pods (increase based on traffic)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # If CPU usage >50%, scale up